export const TEMPLATES = [
  {
    id: "classic",
    name: "Classic Accordion",
    tier: "free",
    previewImage: "https://cdn.shopify.com/s/files/1/0262/4071/2726/files/emptystate-files.png", // placeholder
    description: "A standard, clean accordion FAQ layout.",
    defaultSettings: {
      primaryColor: "#1a1a2e",
      secondaryColor: "#16213e",
      backgroundColor: "#ffffff",
      textColor: "#333333",
      cardBackground: "#ffffff",
      borderColor: "#e5e7eb",
      fontFamily: "Inter",
      headingFontSize: "24",
      bodyFontSize: "15",
      questionFontWeight: "600",
      borderRadius: "6",
      cardPadding: "20",
      itemSpacing: "12",
      containerMaxWidth: "800",
      cardShadow: "sm",
      cardBorderWidth: "1",
      cardHoverEffect: "lift",
      iconStyle: "chevron",
      iconColor: "#6b7280",
    }
  },
  {
    id: "grid",
    name: "Minimalist Grid",
    tier: "starter",
    previewImage: "https://cdn.shopify.com/s/files/1/0262/4071/2726/files/emptystate-files.png",
    description: "Display FAQs in a neat 2-column grid.",
    defaultSettings: {
      primaryColor: "#008060",
      secondaryColor: "#004c3f",
      backgroundColor: "#f4f6f8",
      textColor: "#202223",
      cardBackground: "#ffffff",
      borderColor: "#d1d5db",
      fontFamily: "Roboto",
      headingFontSize: "22",
      bodyFontSize: "14",
      questionFontWeight: "600",
      borderRadius: "10",
      cardPadding: "24",
      itemSpacing: "16",
      containerMaxWidth: "900",
      cardShadow: "md",
      cardBorderWidth: "0",
      cardHoverEffect: "glow",
      iconStyle: "plus",
      iconColor: "#008060",
    }
  },
  {
    id: "card",
    name: "Modern Card",
    tier: "starter",
    previewImage: "https://cdn.shopify.com/s/files/1/0262/4071/2726/files/emptystate-files.png",
    description: "Each FAQ gets its own elevated card.",
    defaultSettings: {
      primaryColor: "#2c6ecb",
      secondaryColor: "#1f5ba6",
      backgroundColor: "#f8f9fc",
      textColor: "#202223",
      cardBackground: "#ffffff",
      borderColor: "#e0e5ee",
      fontFamily: "Outfit",
      headingFontSize: "26",
      bodyFontSize: "15",
      questionFontWeight: "700",
      borderRadius: "14",
      cardPadding: "28",
      itemSpacing: "16",
      containerMaxWidth: "850",
      cardShadow: "lg",
      cardBorderWidth: "0",
      cardHoverEffect: "lift",
      iconStyle: "chevron",
      iconColor: "#2c6ecb",
    }
  },
  {
    id: "split",
    name: "Split Layout",
    tier: "starter",
    previewImage: "https://cdn.shopify.com/s/files/1/0262/4071/2726/files/emptystate-files.png",
    description: "Categories on the left, FAQs on the right.",
    defaultSettings: {
      primaryColor: "#111827",
      secondaryColor: "#374151",
      backgroundColor: "#ffffff",
      textColor: "#374151",
      cardBackground: "#f9fafb",
      borderColor: "#e5e7eb",
      fontFamily: "Inter",
      headingFontSize: "22",
      bodyFontSize: "15",
      questionFontWeight: "600",
      borderRadius: "4",
      cardPadding: "20",
      itemSpacing: "10",
      containerMaxWidth: "900",
      cardShadow: "none",
      cardBorderWidth: "1",
      cardHoverEffect: "border",
      iconStyle: "arrow",
      iconColor: "#111827",
    }
  },
  {
    id: "dark",
    name: "Dark Mode Premium",
    tier: "pro",
    previewImage: "https://cdn.shopify.com/s/files/1/0262/4071/2726/files/emptystate-files.png",
    description: "A sleek, dark-themed accordion for modern stores.",
    defaultSettings: {
      primaryColor: "#a78bfa",
      secondaryColor: "#7c3aed",
      backgroundColor: "#0f0f1a",
      textColor: "#e2e8f0",
      cardBackground: "#1a1a2e",
      borderColor: "#2d2d44",
      fontFamily: "Poppins",
      headingFontSize: "26",
      bodyFontSize: "15",
      questionFontWeight: "600",
      borderRadius: "10",
      cardPadding: "22",
      itemSpacing: "14",
      containerMaxWidth: "800",
      cardShadow: "md",
      cardBorderWidth: "1",
      cardHoverEffect: "glow",
      iconStyle: "chevron",
      iconColor: "#a78bfa",
    }
  },
  {
    id: "masonry",
    name: "Masonry Layout",
    tier: "pro",
    previewImage: "https://cdn.shopify.com/s/files/1/0262/4071/2726/files/emptystate-files.png",
    description: "A Pinterest-style staggered grid of FAQs.",
    defaultSettings: {
      primaryColor: "#059669",
      secondaryColor: "#047857",
      backgroundColor: "#f0fdf4",
      textColor: "#1f2937",
      cardBackground: "#ffffff",
      borderColor: "#d1fae5",
      fontFamily: "Outfit",
      headingFontSize: "24",
      bodyFontSize: "14",
      questionFontWeight: "700",
      borderRadius: "16",
      cardPadding: "24",
      itemSpacing: "16",
      containerMaxWidth: "1000",
      cardShadow: "lg",
      cardBorderWidth: "0",
      cardHoverEffect: "lift",
      iconStyle: "plus",
      iconColor: "#059669",
    }
  }
];

export const getTemplateById = (id) => TEMPLATES.find(t => t.id === id) || TEMPLATES[0];
