name = "FAQify Pro"
client_id = "{{ SHOPIFY_API_KEY }}"
application_url = "{{ APP_URL }}"
embedded = true

[access_scopes]
scopes = "read_products,write_script_tags"

[auth]
redirect_urls = [
  "{{ APP_URL }}/auth/callback",
  "{{ APP_URL }}/auth/shopify/callback",
  "{{ APP_URL }}/api/auth/callback",
  "{{ APP_URL }}/app/approval"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled", "app_subscriptions/update"]
  uri = "/webhooks"

[webhooks.privacy_compliance]
customer_deletion_url = "https://{{ APP_URL }}/webhooks"
customer_data_request_url = "https://{{ APP_URL }}/webhooks"
shop_deletion_url = "https://{{ APP_URL }}/webhooks"

[pos]
embedded = false

[app_proxy]
url = "{{ APP_URL }}"
subpath = "faqify"
prefix = "apps"
