# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7724e554658f3cbf353200d3b1e1b9ce"
name = "faqify-pro"
application_url = "https://faq-design-g7wb.vercel.app"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://faq-design-g7wb.vercel.app/api/auth" ]

[build]
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://faq-design-g7wb.vercel.app"
subpath = "faqify"
prefix = "apps"
